---
- name: hello world
  hosts: default
  become: true

  roles:      
    - role: iac_role_nginx
      vars:
        nginx_extra_conf:
          - filename: nginx_extra_conf/nomad.conf
            destination: /etc/nginx/conf.d/nomad.conf
          - filename: nginx_extra_conf/hello-world.conf
            destination: /etc/nginx/conf.d/hello-world.conf
          - filename: static_site/index.html
            destination: /var/www/default/index.html
